# Auto-generated: drivers/machine/vidhrdw/sndhrdw objects present in the
# full MAME2003-Plus vendor tree but never wired into mame.mak's DRVLIBS.
# KNOWN ISSUE: some of these partially duplicate symbols already provided
# by mame.mak's existing (older-named) files - file-level removal breaks
# other symbols the SAME file uniquely provides. Needs function-level
# reconciliation, not done yet - see session notes.

DRVLIBS += $(OBJ)/fullset.a

$(OBJ)/fullset.a: \
	$(OBJ)/drivers/1945kiii.o \
	$(OBJ)/drivers/8080bw_drivers.o \
	$(OBJ)/drivers/ashnojoe.o \
	$(OBJ)/drivers/backfire.o \
	$(OBJ)/drivers/bishi.o \
	$(OBJ)/drivers/calorie.o \
	$(OBJ)/drivers/compgolf.o \
	$(OBJ)/drivers/crospang.o \
	$(OBJ)/drivers/darkmist.o \
	$(OBJ)/drivers/dblewing.o \
	$(OBJ)/drivers/deco156.o \
	$(OBJ)/drivers/deco_mlc.o \
	$(OBJ)/drivers/djmain.o \
	$(OBJ)/drivers/dorachan.o \
	$(OBJ)/drivers/driver_denjinmk.o \
	$(OBJ)/drivers/embargo.o \
	$(OBJ)/drivers/funybubl.o \
	$(OBJ)/drivers/fuukifg2.o \
	$(OBJ)/drivers/goal92.o \
	$(OBJ)/drivers/homerun.o \
	$(OBJ)/drivers/inufuku.o \
	$(OBJ)/drivers/jchan.o \
	$(OBJ)/drivers/jcross.o \
	$(OBJ)/drivers/jollyjgr.o \
	$(OBJ)/drivers/konamigq.o \
	$(OBJ)/drivers/ladyfrog.o \
	$(OBJ)/drivers/lethal.o \
	$(OBJ)/drivers/madalien.o \
	$(OBJ)/drivers/malzak.o \
	$(OBJ)/drivers/marinedt.o \
	$(OBJ)/drivers/mirax.o \
	$(OBJ)/drivers/model1.o \
	$(OBJ)/drivers/mogura.o \
	$(OBJ)/drivers/mwarr.o \
	$(OBJ)/drivers/n8080.o \
	$(OBJ)/drivers/namcos10.o \
	$(OBJ)/drivers/namcos12.o \
	$(OBJ)/drivers/pturn.o \
	$(OBJ)/drivers/quizpani.o \
	$(OBJ)/drivers/rabbit.o \
	$(OBJ)/drivers/runaway.o \
	$(OBJ)/drivers/seattle.o \
	$(OBJ)/drivers/segas16b.o \
	$(OBJ)/drivers/segas32.o \
	$(OBJ)/drivers/segaxbd.o \
	$(OBJ)/drivers/speedatk.o \
	$(OBJ)/drivers/sprint8.o \
	$(OBJ)/drivers/sspeedr.o \
	$(OBJ)/drivers/strvmstr.o \
	$(OBJ)/drivers/stvhacks.o \
	$(OBJ)/drivers/supertnk.o \
	$(OBJ)/drivers/suprridr.o \
	$(OBJ)/drivers/tatsumi.o \
	$(OBJ)/drivers/tceptor.o \
	$(OBJ)/drivers/tryout.o \
	$(OBJ)/drivers/vamphalf.o \
	$(OBJ)/drivers/vmetal.o \
	$(OBJ)/drivers/yumefuda.o \
	$(OBJ)/machine/6522via.o \
	$(OBJ)/machine/6532riot.o \
	$(OBJ)/machine/6821pia.o \
	$(OBJ)/machine/74123.o \
	$(OBJ)/machine/74148.o \
	$(OBJ)/machine/74153.o \
	$(OBJ)/machine/7474.o \
	$(OBJ)/machine/8255ppi.o \
	$(OBJ)/machine/ajax_machine.o \
	$(OBJ)/machine/am53cf96.o \
	$(OBJ)/machine/arkanoid_machine.o \
	$(OBJ)/machine/asteroid_machine.o \
	$(OBJ)/machine/astrocde_machine.o \
	$(OBJ)/machine/atarifb_machine.o \
	$(OBJ)/machine/avalnche_machine.o \
	$(OBJ)/machine/bagman_machine.o \
	$(OBJ)/machine/balsente_machine.o \
	$(OBJ)/machine/beezer_machine.o \
	$(OBJ)/machine/berzerk_machine.o \
	$(OBJ)/machine/bigevglf_machine.o \
	$(OBJ)/machine/bsktball_machine.o \
	$(OBJ)/machine/btime_machine.o \
	$(OBJ)/machine/bublbobl_machine.o \
	$(OBJ)/machine/buggychl_machine.o \
	$(OBJ)/machine/capbowl_machine.o \
	$(OBJ)/machine/carpolo_machine.o \
	$(OBJ)/machine/cchasm_machine.o \
	$(OBJ)/machine/chaknpop_machine.o \
	$(OBJ)/machine/clayshoo_machine.o \
	$(OBJ)/machine/copsnrob_machine.o \
	$(OBJ)/machine/cps2crypt.o \
	$(OBJ)/machine/dec0_machine.o \
	$(OBJ)/machine/decocass_machine.o \
	$(OBJ)/machine/docastle_machine.o \
	$(OBJ)/machine/eeprom.o \
	$(OBJ)/machine/equites_machine.o \
	$(OBJ)/machine/exctsccr_machine.o \
	$(OBJ)/machine/fd1089.o \
	$(OBJ)/machine/flstory_machine.o \
	$(OBJ)/machine/gaelco2_machine.o \
	$(OBJ)/machine/gaplus_machine.o \
	$(OBJ)/machine/geebee_machine.o \
	$(OBJ)/machine/grchamp_machine.o \
	$(OBJ)/machine/harddriv_machine.o \
	$(OBJ)/machine/idectrl.o \
	$(OBJ)/machine/irobot_machine.o \
	$(OBJ)/machine/jackal_machine.o \
	$(OBJ)/machine/konami_machine.o \
	$(OBJ)/machine/konamigx_machine.o \
	$(OBJ)/machine/kyugo_machine.o \
	$(OBJ)/machine/leland_machine.o \
	$(OBJ)/machine/leprechn_machine.o \
	$(OBJ)/machine/lkage_machine.o \
	$(OBJ)/machine/lsasquad_machine.o \
	$(OBJ)/machine/mathbox.o \
	$(OBJ)/machine/mb87078.o \
	$(OBJ)/machine/mc8123.o \
	$(OBJ)/machine/mexico86_machine.o \
	$(OBJ)/machine/mhavoc_machine.o \
	$(OBJ)/machine/midtunit_machine.o \
	$(OBJ)/machine/midwunit_machine.o \
	$(OBJ)/machine/midyunit_machine.o \
	$(OBJ)/machine/missile_machine.o \
	$(OBJ)/machine/model1_machine.o \
	$(OBJ)/machine/namcoio_machine.o \
	$(OBJ)/machine/namcond1_machine.o \
	$(OBJ)/machine/namcos1_machine.o \
	$(OBJ)/machine/namcos2_machine.o \
	$(OBJ)/machine/neogeo_machine.o \
	$(OBJ)/machine/nitedrvr_machine.o \
	$(OBJ)/machine/nycaptor_machine.o \
	$(OBJ)/machine/opwolf_machine.o \
	$(OBJ)/machine/pgmprot_machine.o \
	$(OBJ)/machine/pgmy2ks.o \
	$(OBJ)/machine/pitnrun_machine.o \
	$(OBJ)/machine/playch10_machine.o \
	$(OBJ)/machine/psx_machine.o \
	$(OBJ)/machine/qix_machine.o \
	$(OBJ)/machine/rainbow_machine.o \
	$(OBJ)/machine/random.o \
	$(OBJ)/machine/retofinv_machine.o \
	$(OBJ)/machine/sbrkout_machine.o \
	$(OBJ)/machine/scramble_machine.o \
	$(OBJ)/machine/scudsp.o \
	$(OBJ)/machine/sega_machine.o \
	$(OBJ)/machine/segaic16.o \
	$(OBJ)/machine/segar_machine.o \
	$(OBJ)/machine/segas32.o \
	$(OBJ)/machine/simpsons_machine.o \
	$(OBJ)/machine/slapfght_machine.o \
	$(OBJ)/machine/snes_machine.o \
	$(OBJ)/machine/spiders_machine.o \
	$(OBJ)/machine/stactics_machine.o \
	$(OBJ)/machine/starwars_machine.o \
	$(OBJ)/machine/stfight_machine.o \
	$(OBJ)/machine/strtheat.o \
	$(OBJ)/machine/stvcd.o \
	$(OBJ)/machine/subs_machine.o \
	$(OBJ)/machine/system16_machine.o \
	$(OBJ)/machine/system24_machine.o \
	$(OBJ)/machine/taitosj_machine.o \
	$(OBJ)/machine/tatsumi.o \
	$(OBJ)/machine/ticket.o \
	$(OBJ)/machine/tmp68301.o \
	$(OBJ)/machine/tnzs_machine.o \
	$(OBJ)/machine/toaplan1_machine.o \
	$(OBJ)/machine/turbo_machine.o \
	$(OBJ)/machine/twincobr_machine.o \
	$(OBJ)/machine/volfied_machine.o \
	$(OBJ)/machine/vsnes_machine.o \
	$(OBJ)/machine/williams_machine.o \
	$(OBJ)/machine/wrally_machine.o \
	$(OBJ)/machine/xevious_machine.o \
	$(OBJ)/machine/z80fmly.o \
	$(OBJ)/sndhrdw/8080bw_sndhrdw.o \
	$(OBJ)/sndhrdw/asteroid_sndhrdw.o \
	$(OBJ)/sndhrdw/astinvad_sndhrdw.o \
	$(OBJ)/sndhrdw/astrocde_sndhrdw.o \
	$(OBJ)/sndhrdw/astrof_sndhrdw.o \
	$(OBJ)/sndhrdw/ataridis_sndhrdw.o \
	$(OBJ)/sndhrdw/aztarac_sndhrdw.o \
	$(OBJ)/sndhrdw/berzerk_sndhrdw.o \
	$(OBJ)/sndhrdw/bzone_sndhrdw.o \
	$(OBJ)/sndhrdw/cage_sndhrdw.o \
	$(OBJ)/sndhrdw/cchasm_sndhrdw.o \
	$(OBJ)/sndhrdw/cclimber_sndhrdw.o \
	$(OBJ)/sndhrdw/cinemat_sndhrdw.o \
	$(OBJ)/sndhrdw/cyberbal_sndhrdw.o \
	$(OBJ)/sndhrdw/dkong_sndhrdw.o \
	$(OBJ)/sndhrdw/exidy440_sndhrdw.o \
	$(OBJ)/sndhrdw/exidy_sndhrdw.o \
	$(OBJ)/sndhrdw/flower_sndhrdw.o \
	$(OBJ)/sndhrdw/galaxian_sndhrdw.o \
	$(OBJ)/sndhrdw/geebee_sndhrdw.o \
	$(OBJ)/sndhrdw/gomoku_sndhrdw.o \
	$(OBJ)/sndhrdw/gottlieb_sndhrdw.o \
	$(OBJ)/sndhrdw/gotya_sndhrdw.o \
	$(OBJ)/sndhrdw/gridlee_sndhrdw.o \
	$(OBJ)/sndhrdw/gyruss_sndhrdw.o \
	$(OBJ)/sndhrdw/harddriv_sndhrdw.o \
	$(OBJ)/sndhrdw/jaguar_sndhrdw.o \
	$(OBJ)/sndhrdw/leland_sndhrdw.o \
	$(OBJ)/sndhrdw/m72_sndhrdw.o \
	$(OBJ)/sndhrdw/mario_sndhrdw.o \
	$(OBJ)/sndhrdw/mcr_sndhrdw.o \
	$(OBJ)/sndhrdw/meadows_sndhrdw.o \
	$(OBJ)/sndhrdw/phoenix_sndhrdw.o \
	$(OBJ)/sndhrdw/polepos_sndhrdw.o \
	$(OBJ)/sndhrdw/polyplay_sndhrdw.o \
	$(OBJ)/sndhrdw/rastan_sndhrdw.o \
	$(OBJ)/sndhrdw/redalert_sndhrdw.o \
	$(OBJ)/sndhrdw/rockola_sndhrdw.o \
	$(OBJ)/sndhrdw/scramble_sndhrdw.o \
	$(OBJ)/sndhrdw/sega_sndhrdw.o \
	$(OBJ)/sndhrdw/segar_sndhrdw.o \
	$(OBJ)/sndhrdw/senjyo_sndhrdw.o \
	$(OBJ)/sndhrdw/snes_sndhrdw.o \
	$(OBJ)/sndhrdw/starwars_sndhrdw.o \
	$(OBJ)/sndhrdw/system16_sndhrdw.o \
	$(OBJ)/sndhrdw/t5182.o \
	$(OBJ)/sndhrdw/taito_f3_sndhrdw.o \
	$(OBJ)/sndhrdw/timeplt_sndhrdw.o \
	$(OBJ)/sndhrdw/trackfld_sndhrdw.o \
	$(OBJ)/sndhrdw/triplhnt.o \
	$(OBJ)/sndhrdw/warpwarp_sndhrdw.o \
	$(OBJ)/sndhrdw/williams_sndhrdw.o \
	$(OBJ)/sndhrdw/wiping_sndhrdw.o \
	$(OBJ)/sndhrdw/zaxxon_sndhrdw.o \
	$(OBJ)/vidhrdw/1942_vidhrdw.o \
	$(OBJ)/vidhrdw/1943_vidhrdw.o \
	$(OBJ)/vidhrdw/40love_vidhrdw.o \
	$(OBJ)/vidhrdw/4enraya_vidhrdw.o \
	$(OBJ)/vidhrdw/8080bw_vidhrdw.o \
	$(OBJ)/vidhrdw/88games_vidhrdw.o \
	$(OBJ)/vidhrdw/actfancr_vidhrdw.o \
	$(OBJ)/vidhrdw/aeroboto_vidhrdw.o \
	$(OBJ)/vidhrdw/aerofgt_vidhrdw.o \
	$(OBJ)/vidhrdw/afega_vidhrdw.o \
	$(OBJ)/vidhrdw/airbustr_vidhrdw.o \
	$(OBJ)/vidhrdw/ajax_vidhrdw.o \
	$(OBJ)/vidhrdw/aliens_vidhrdw.o \
	$(OBJ)/vidhrdw/alpha68k_vidhrdw.o \
	$(OBJ)/vidhrdw/ambush_vidhrdw.o \
	$(OBJ)/vidhrdw/amspdwy_vidhrdw.o \
	$(OBJ)/vidhrdw/angelkds_vidhrdw.o \
	$(OBJ)/vidhrdw/appoooh_vidhrdw.o \
	$(OBJ)/vidhrdw/aquarium_vidhrdw.o \
	$(OBJ)/vidhrdw/arabian_vidhrdw.o \
	$(OBJ)/vidhrdw/arcadecl_vidhrdw.o \
	$(OBJ)/vidhrdw/argus_vidhrdw.o \
	$(OBJ)/vidhrdw/arkanoid_vidhrdw.o \
	$(OBJ)/vidhrdw/armedf_vidhrdw.o \
	$(OBJ)/vidhrdw/artmagic_vidhrdw.o \
	$(OBJ)/vidhrdw/ashnojoe_vidhrdw.o \
	$(OBJ)/vidhrdw/asterix_vidhrdw.o \
	$(OBJ)/vidhrdw/astinvad_vidhrdw.o \
	$(OBJ)/vidhrdw/astrocde_vidhrdw.o \
	$(OBJ)/vidhrdw/astrof_vidhrdw.o \
	$(OBJ)/vidhrdw/asuka_vidhrdw.o \
	$(OBJ)/vidhrdw/atarifb_vidhrdw.o \
	$(OBJ)/vidhrdw/atarig1_vidhrdw.o \
	$(OBJ)/vidhrdw/atarig42_vidhrdw.o \
	$(OBJ)/vidhrdw/atarigt_vidhrdw.o \
	$(OBJ)/vidhrdw/atarigx2_vidhrdw.o \
	$(OBJ)/vidhrdw/atarimo_vidhrdw.o \
	$(OBJ)/vidhrdw/atarirle_vidhrdw.o \
	$(OBJ)/vidhrdw/atarisy1_vidhrdw.o \
	$(OBJ)/vidhrdw/atarisy2_vidhrdw.o \
	$(OBJ)/vidhrdw/atetris_vidhrdw.o \
	$(OBJ)/vidhrdw/avalnche_vidhrdw.o \
	$(OBJ)/vidhrdw/avgdvg_vidhrdw.o \
	$(OBJ)/vidhrdw/aztarac_vidhrdw.o \
	$(OBJ)/vidhrdw/badlands_vidhrdw.o \
	$(OBJ)/vidhrdw/bagman_vidhrdw.o \
	$(OBJ)/vidhrdw/balsente_vidhrdw.o \
	$(OBJ)/vidhrdw/bankp_vidhrdw.o \
	$(OBJ)/vidhrdw/baraduke_vidhrdw.o \
	$(OBJ)/vidhrdw/batman_vidhrdw.o \
	$(OBJ)/vidhrdw/battlane_vidhrdw.o \
	$(OBJ)/vidhrdw/battlera_vidhrdw.o \
	$(OBJ)/vidhrdw/battlex_vidhrdw.o \
	$(OBJ)/vidhrdw/battlnts_vidhrdw.o \
	$(OBJ)/vidhrdw/bbusters_vidhrdw.o \
	$(OBJ)/vidhrdw/beaminv_vidhrdw.o \
	$(OBJ)/vidhrdw/beathead_vidhrdw.o \
	$(OBJ)/vidhrdw/beezer_vidhrdw.o \
	$(OBJ)/vidhrdw/berzerk_vidhrdw.o \
	$(OBJ)/vidhrdw/bigevglf_vidhrdw.o \
	$(OBJ)/vidhrdw/bigstrkb_vidhrdw.o \
	$(OBJ)/vidhrdw/bionicc_vidhrdw.o \
	$(OBJ)/vidhrdw/bishi_vidhrdw.o \
	$(OBJ)/vidhrdw/bking2_vidhrdw.o \
	$(OBJ)/vidhrdw/bladestl_vidhrdw.o \
	$(OBJ)/vidhrdw/blktiger_vidhrdw.o \
	$(OBJ)/vidhrdw/blmbycar_vidhrdw.o \
	$(OBJ)/vidhrdw/blockade_vidhrdw.o \
	$(OBJ)/vidhrdw/blockhl_vidhrdw.o \
	$(OBJ)/vidhrdw/blockout_vidhrdw.o \
	$(OBJ)/vidhrdw/bloodbro_vidhrdw.o \
	$(OBJ)/vidhrdw/blstroid_vidhrdw.o \
	$(OBJ)/vidhrdw/blueprnt_vidhrdw.o \
	$(OBJ)/vidhrdw/bogeyman_vidhrdw.o \
	$(OBJ)/vidhrdw/bombjack_vidhrdw.o \
	$(OBJ)/vidhrdw/bosco_vidhrdw.o \
	$(OBJ)/vidhrdw/bottom9_vidhrdw.o \
	$(OBJ)/vidhrdw/boxer_vidhrdw.o \
	$(OBJ)/vidhrdw/brkthru_vidhrdw.o \
	$(OBJ)/vidhrdw/bsktball_vidhrdw.o \
	$(OBJ)/vidhrdw/btime_vidhrdw.o \
	$(OBJ)/vidhrdw/btoads_vidhrdw.o \
	$(OBJ)/vidhrdw/bublbobl_vidhrdw.o \
	$(OBJ)/vidhrdw/buggychl_vidhrdw.o \
	$(OBJ)/vidhrdw/bwing_vidhrdw.o \
	$(OBJ)/vidhrdw/cabal_vidhrdw.o \
	$(OBJ)/vidhrdw/canyon_vidhrdw.o \
	$(OBJ)/vidhrdw/capbowl_vidhrdw.o \
	$(OBJ)/vidhrdw/carjmbre_vidhrdw.o \
	$(OBJ)/vidhrdw/carpolo_vidhrdw.o \
	$(OBJ)/vidhrdw/cave_vidhrdw.o \
	$(OBJ)/vidhrdw/cbasebal_vidhrdw.o \
	$(OBJ)/vidhrdw/cbuster_vidhrdw.o \
	$(OBJ)/vidhrdw/ccastles_vidhrdw.o \
	$(OBJ)/vidhrdw/cchasm_vidhrdw.o \
	$(OBJ)/vidhrdw/cclimber_vidhrdw.o \
	$(OBJ)/vidhrdw/centiped_vidhrdw.o \
	$(OBJ)/vidhrdw/chaknpop_vidhrdw.o \
	$(OBJ)/vidhrdw/champbas_vidhrdw.o \
	$(OBJ)/vidhrdw/cheekyms_vidhrdw.o \
	$(OBJ)/vidhrdw/chqflag_vidhrdw.o \
	$(OBJ)/vidhrdw/cinemat_vidhrdw.o \
	$(OBJ)/vidhrdw/circus_vidhrdw.o \
	$(OBJ)/vidhrdw/circusc_vidhrdw.o \
	$(OBJ)/vidhrdw/cischeat_vidhrdw.o \
	$(OBJ)/vidhrdw/citycon_vidhrdw.o \
	$(OBJ)/vidhrdw/clayshoo_vidhrdw.o \
	$(OBJ)/vidhrdw/cloak_vidhrdw.o \
	$(OBJ)/vidhrdw/cloud9_vidhrdw.o \
	$(OBJ)/vidhrdw/clshroad_vidhrdw.o \
	$(OBJ)/vidhrdw/cninja_vidhrdw.o \
	$(OBJ)/vidhrdw/combatsc_vidhrdw.o \
	$(OBJ)/vidhrdw/commando_vidhrdw.o \
	$(OBJ)/vidhrdw/compgolf_vidhrdw.o \
	$(OBJ)/vidhrdw/contra_vidhrdw.o \
	$(OBJ)/vidhrdw/cop01_vidhrdw.o \
	$(OBJ)/vidhrdw/copsnrob_vidhrdw.o \
	$(OBJ)/vidhrdw/cosmic_vidhrdw.o \
	$(OBJ)/vidhrdw/cps1_vidhrdw.o \
	$(OBJ)/vidhrdw/crbaloon_vidhrdw.o \
	$(OBJ)/vidhrdw/crgolf_vidhrdw.o \
	$(OBJ)/vidhrdw/crimfght_vidhrdw.o \
	$(OBJ)/vidhrdw/crospang_vidhrdw.o \
	$(OBJ)/vidhrdw/crshrace_vidhrdw.o \
	$(OBJ)/vidhrdw/cvs_vidhrdw.o \
	$(OBJ)/vidhrdw/cyberbal_vidhrdw.o \
	$(OBJ)/vidhrdw/darius_vidhrdw.o \
	$(OBJ)/vidhrdw/darkmist_vidhrdw.o \
	$(OBJ)/vidhrdw/darkseal_vidhrdw.o \
	$(OBJ)/vidhrdw/dassault_vidhrdw.o \
	$(OBJ)/vidhrdw/dbz2_vidhrdw.o \
	$(OBJ)/vidhrdw/dcon_vidhrdw.o \
	$(OBJ)/vidhrdw/dday_vidhrdw.o \
	$(OBJ)/vidhrdw/ddragon3_vidhrdw.o \
	$(OBJ)/vidhrdw/ddragon_vidhrdw.o \
	$(OBJ)/vidhrdw/ddrible_vidhrdw.o \
	$(OBJ)/vidhrdw/deadang_vidhrdw.o \
	$(OBJ)/vidhrdw/dec0_vidhrdw.o \
	$(OBJ)/vidhrdw/dec8_vidhrdw.o \
	$(OBJ)/vidhrdw/deco32_vidhrdw.o \
	$(OBJ)/vidhrdw/deco_mlc_vidhrdw.o \
	$(OBJ)/vidhrdw/decocass_vidhrdw.o \
	$(OBJ)/vidhrdw/deniam_vidhrdw.o \
	$(OBJ)/vidhrdw/destroyr_vidhrdw.o \
	$(OBJ)/vidhrdw/digdug_vidhrdw.o \
	$(OBJ)/vidhrdw/diverboy_vidhrdw.o \
	$(OBJ)/vidhrdw/djboy_vidhrdw.o \
	$(OBJ)/vidhrdw/djmain_vidhrdw.o \
	$(OBJ)/vidhrdw/dkong_vidhrdw.o \
	$(OBJ)/vidhrdw/docastle_vidhrdw.o \
	$(OBJ)/vidhrdw/dogfgt_vidhrdw.o \
	$(OBJ)/vidhrdw/dooyong_vidhrdw.o \
	$(OBJ)/vidhrdw/dorachan_vidhrdw.o \
	$(OBJ)/vidhrdw/dotrikun_vidhrdw.o \
	$(OBJ)/vidhrdw/dragrace_vidhrdw.o \
	$(OBJ)/vidhrdw/drgnmst_vidhrdw.o \
	$(OBJ)/vidhrdw/dribling_vidhrdw.o \
	$(OBJ)/vidhrdw/drmicro_vidhrdw.o \
	$(OBJ)/vidhrdw/dynax_vidhrdw.o \
	$(OBJ)/vidhrdw/dynduke_vidhrdw.o \
	$(OBJ)/vidhrdw/epos_vidhrdw.o \
	$(OBJ)/vidhrdw/eprom_vidhrdw.o \
	$(OBJ)/vidhrdw/equites_vidhrdw.o \
	$(OBJ)/vidhrdw/esd16_vidhrdw.o \
	$(OBJ)/vidhrdw/espial_vidhrdw.o \
	$(OBJ)/vidhrdw/exctsccr_vidhrdw.o \
	$(OBJ)/vidhrdw/exedexes_vidhrdw.o \
	$(OBJ)/vidhrdw/exerion_vidhrdw.o \
	$(OBJ)/vidhrdw/exidy440_vidhrdw.o \
	$(OBJ)/vidhrdw/exidy_vidhrdw.o \
	$(OBJ)/vidhrdw/exprraid_vidhrdw.o \
	$(OBJ)/vidhrdw/exterm_vidhrdw.o \
	$(OBJ)/vidhrdw/exzisus_vidhrdw.o \
	$(OBJ)/vidhrdw/f1gp_vidhrdw.o \
	$(OBJ)/vidhrdw/fantland_vidhrdw.o \
	$(OBJ)/vidhrdw/fastfred_vidhrdw.o \
	$(OBJ)/vidhrdw/fastlane_vidhrdw.o \
	$(OBJ)/vidhrdw/finalizr_vidhrdw.o \
	$(OBJ)/vidhrdw/firetrap_vidhrdw.o \
	$(OBJ)/vidhrdw/firetrk_vidhrdw.o \
	$(OBJ)/vidhrdw/fitfight_vidhrdw.o \
	$(OBJ)/vidhrdw/flkatck_vidhrdw.o \
	$(OBJ)/vidhrdw/flower_vidhrdw.o \
	$(OBJ)/vidhrdw/flstory_vidhrdw.o \
	$(OBJ)/vidhrdw/flyball_vidhrdw.o \
	$(OBJ)/vidhrdw/foodf_vidhrdw.o \
	$(OBJ)/vidhrdw/freekick_vidhrdw.o \
	$(OBJ)/vidhrdw/fromanc2_vidhrdw.o \
	$(OBJ)/vidhrdw/fromance_vidhrdw.o \
	$(OBJ)/vidhrdw/funkybee_vidhrdw.o \
	$(OBJ)/vidhrdw/funkyjet_vidhrdw.o \
	$(OBJ)/vidhrdw/fuukifg2_vidhrdw.o \
	$(OBJ)/vidhrdw/fuukifg3_vidhrdw.o \
	$(OBJ)/vidhrdw/gaelco2_vidhrdw.o \
	$(OBJ)/vidhrdw/gaelco_vidhrdw.o \
	$(OBJ)/vidhrdw/gaiden_vidhrdw.o \
	$(OBJ)/vidhrdw/galaga_vidhrdw.o \
	$(OBJ)/vidhrdw/galaxian_vidhrdw.o \
	$(OBJ)/vidhrdw/galivan_vidhrdw.o \
	$(OBJ)/vidhrdw/galpani2_vidhrdw.o \
	$(OBJ)/vidhrdw/galpanic_vidhrdw.o \
	$(OBJ)/vidhrdw/galspnbl_vidhrdw.o \
	$(OBJ)/vidhrdw/gameplan_vidhrdw.o \
	$(OBJ)/vidhrdw/gaplus_vidhrdw.o \
	$(OBJ)/vidhrdw/gauntlet_vidhrdw.o \
	$(OBJ)/vidhrdw/gberet_vidhrdw.o \
	$(OBJ)/vidhrdw/gbusters_vidhrdw.o \
	$(OBJ)/vidhrdw/gcpinbal_vidhrdw.o \
	$(OBJ)/vidhrdw/geebee_vidhrdw.o \
	$(OBJ)/vidhrdw/generic.o \
	$(OBJ)/vidhrdw/gijoe_vidhrdw.o \
	$(OBJ)/vidhrdw/ginganin_vidhrdw.o \
	$(OBJ)/vidhrdw/gladiatr_vidhrdw.o \
	$(OBJ)/vidhrdw/glass_vidhrdw.o \
	$(OBJ)/vidhrdw/gng_vidhrdw.o \
	$(OBJ)/vidhrdw/goal92_vidhrdw.o \
	$(OBJ)/vidhrdw/goindol_vidhrdw.o \
	$(OBJ)/vidhrdw/gomoku_vidhrdw.o \
	$(OBJ)/vidhrdw/gotcha_vidhrdw.o \
	$(OBJ)/vidhrdw/gottlieb_vidhrdw.o \
	$(OBJ)/vidhrdw/gotya_vidhrdw.o \
	$(OBJ)/vidhrdw/gradius3_vidhrdw.o \
	$(OBJ)/vidhrdw/grchamp_vidhrdw.o \
	$(OBJ)/vidhrdw/gridlee_vidhrdw.o \
	$(OBJ)/vidhrdw/groundfx_vidhrdw.o \
	$(OBJ)/vidhrdw/gstriker_vidhrdw.o \
	$(OBJ)/vidhrdw/gsword_vidhrdw.o \
	$(OBJ)/vidhrdw/gumbo_vidhrdw.o \
	$(OBJ)/vidhrdw/gunbustr_vidhrdw.o \
	$(OBJ)/vidhrdw/gundealr_vidhrdw.o \
	$(OBJ)/vidhrdw/gunsmoke_vidhrdw.o \
	$(OBJ)/vidhrdw/gyruss_vidhrdw.o \
	$(OBJ)/vidhrdw/hanaawas_vidhrdw.o \
	$(OBJ)/vidhrdw/harddriv_vidhrdw.o \
	$(OBJ)/vidhrdw/hcastle_vidhrdw.o \
	$(OBJ)/vidhrdw/hexa_vidhrdw.o \
	$(OBJ)/vidhrdw/hexion_vidhrdw.o \
	$(OBJ)/vidhrdw/higemaru_vidhrdw.o \
	$(OBJ)/vidhrdw/hitme_vidhrdw.o \
	$(OBJ)/vidhrdw/hnayayoi_vidhrdw.o \
	$(OBJ)/vidhrdw/holeland_vidhrdw.o \
	$(OBJ)/vidhrdw/homedata_vidhrdw.o \
	$(OBJ)/vidhrdw/homerun_vidhrdw.o \
	$(OBJ)/vidhrdw/hyhoo_vidhrdw.o \
	$(OBJ)/vidhrdw/hyperspt_vidhrdw.o \
	$(OBJ)/vidhrdw/hyprduel_vidhrdw.o \
	$(OBJ)/vidhrdw/ikki_vidhrdw.o \
	$(OBJ)/vidhrdw/inufuku_vidhrdw.o \
	$(OBJ)/vidhrdw/iqblock_vidhrdw.o \
	$(OBJ)/vidhrdw/irobot_vidhrdw.o \
	$(OBJ)/vidhrdw/ironhors_vidhrdw.o \
	$(OBJ)/vidhrdw/itech32_vidhrdw.o \
	$(OBJ)/vidhrdw/itech8_vidhrdw.o \
	$(OBJ)/vidhrdw/jack_vidhrdw.o \
	$(OBJ)/vidhrdw/jackal_vidhrdw.o \
	$(OBJ)/vidhrdw/jaguar_vidhrdw.o \
	$(OBJ)/vidhrdw/jailbrek_vidhrdw.o \
	$(OBJ)/vidhrdw/jcross_vidhrdw.o \
	$(OBJ)/vidhrdw/jedi_vidhrdw.o \
	$(OBJ)/vidhrdw/kaneko16_vidhrdw.o \
	$(OBJ)/vidhrdw/kangaroo_vidhrdw.o \
	$(OBJ)/vidhrdw/karnov_vidhrdw.o \
	$(OBJ)/vidhrdw/kchamp_vidhrdw.o \
	$(OBJ)/vidhrdw/kickgoal_vidhrdw.o \
	$(OBJ)/vidhrdw/kingobox_vidhrdw.o \
	$(OBJ)/vidhrdw/kinst_vidhrdw.o \
	$(OBJ)/vidhrdw/klax_vidhrdw.o \
	$(OBJ)/vidhrdw/kncljoe_vidhrdw.o \
	$(OBJ)/vidhrdw/konamigx_vidhrdw.o \
	$(OBJ)/vidhrdw/kopunch_vidhrdw.o \
	$(OBJ)/vidhrdw/kyugo_vidhrdw.o \
	$(OBJ)/vidhrdw/labyrunr_vidhrdw.o \
	$(OBJ)/vidhrdw/ladybug_vidhrdw.o \
	$(OBJ)/vidhrdw/ladyfrog_vidhrdw.o \
	$(OBJ)/vidhrdw/lasso_vidhrdw.o \
	$(OBJ)/vidhrdw/lastduel_vidhrdw.o \
	$(OBJ)/vidhrdw/lazercmd_vidhrdw.o \
	$(OBJ)/vidhrdw/legionna_vidhrdw.o \
	$(OBJ)/vidhrdw/leland_vidhrdw.o \
	$(OBJ)/vidhrdw/lemmings_vidhrdw.o \
	$(OBJ)/vidhrdw/leprechn_vidhrdw.o \
	$(OBJ)/vidhrdw/lethal_vidhrdw.o \
	$(OBJ)/vidhrdw/lethalj_vidhrdw.o \
	$(OBJ)/vidhrdw/liberate_vidhrdw.o \
	$(OBJ)/vidhrdw/liberatr_vidhrdw.o \
	$(OBJ)/vidhrdw/lkage_vidhrdw.o \
	$(OBJ)/vidhrdw/lsasquad_vidhrdw.o \
	$(OBJ)/vidhrdw/lwings_vidhrdw.o \
	$(OBJ)/vidhrdw/m107_vidhrdw.o \
	$(OBJ)/vidhrdw/m62_vidhrdw.o \
	$(OBJ)/vidhrdw/m72_vidhrdw.o \
	$(OBJ)/vidhrdw/m79amb_vidhrdw.o \
	$(OBJ)/vidhrdw/m90_vidhrdw.o \
	$(OBJ)/vidhrdw/m92_vidhrdw.o \
	$(OBJ)/vidhrdw/macrossp_vidhrdw.o \
	$(OBJ)/vidhrdw/madmotor_vidhrdw.o \
	$(OBJ)/vidhrdw/magmax_vidhrdw.o \
	$(OBJ)/vidhrdw/mainevt_vidhrdw.o \
	$(OBJ)/vidhrdw/mainsnk_vidhrdw.o \
	$(OBJ)/vidhrdw/malzak_vidhrdw.o \
	$(OBJ)/vidhrdw/mappy_vidhrdw.o \
	$(OBJ)/vidhrdw/marineb_vidhrdw.o \
	$(OBJ)/vidhrdw/mario_vidhrdw.o \
	$(OBJ)/vidhrdw/markham_vidhrdw.o \
	$(OBJ)/vidhrdw/marvins_vidhrdw.o \
	$(OBJ)/vidhrdw/matmania_vidhrdw.o \
	$(OBJ)/vidhrdw/matrix3d.o \
	$(OBJ)/vidhrdw/mayumi_vidhrdw.o \
	$(OBJ)/vidhrdw/mcatadv_vidhrdw.o \
	$(OBJ)/vidhrdw/mcr12_vidhrdw.o \
	$(OBJ)/vidhrdw/mcr3_vidhrdw.o \
	$(OBJ)/vidhrdw/mcr68_vidhrdw.o \
	$(OBJ)/vidhrdw/meadows_vidhrdw.o \
	$(OBJ)/vidhrdw/megasys1_vidhrdw.o \
	$(OBJ)/vidhrdw/megazone_vidhrdw.o \
	$(OBJ)/vidhrdw/mermaid_vidhrdw.o \
	$(OBJ)/vidhrdw/metlclsh_vidhrdw.o \
	$(OBJ)/vidhrdw/metro_vidhrdw.o \
	$(OBJ)/vidhrdw/mexico86_vidhrdw.o \
	$(OBJ)/vidhrdw/midtunit_vidhrdw.o \
	$(OBJ)/vidhrdw/midvunit_vidhrdw.o \
	$(OBJ)/vidhrdw/midyunit_vidhrdw.o \
	$(OBJ)/vidhrdw/mikie_vidhrdw.o \
	$(OBJ)/vidhrdw/minivadr_vidhrdw.o \
	$(OBJ)/vidhrdw/missile_vidhrdw.o \
	$(OBJ)/vidhrdw/mitchell_vidhrdw.o \
	$(OBJ)/vidhrdw/mjkjidai_vidhrdw.o \
	$(OBJ)/vidhrdw/mjsister_vidhrdw.o \
	$(OBJ)/vidhrdw/mnight_vidhrdw.o \
	$(OBJ)/vidhrdw/model1_vidhrdw.o \
	$(OBJ)/vidhrdw/mole_vidhrdw.o \
	$(OBJ)/vidhrdw/momoko_vidhrdw.o \
	$(OBJ)/vidhrdw/moo_vidhrdw.o \
	$(OBJ)/vidhrdw/mosaic_vidhrdw.o \
	$(OBJ)/vidhrdw/mouser_vidhrdw.o \
	$(OBJ)/vidhrdw/mpatrol_vidhrdw.o \
	$(OBJ)/vidhrdw/mrdo_vidhrdw.o \
	$(OBJ)/vidhrdw/mrflea_vidhrdw.o \
	$(OBJ)/vidhrdw/mrjong_vidhrdw.o \
	$(OBJ)/vidhrdw/ms32_vidhrdw.o \
	$(OBJ)/vidhrdw/msisaac_vidhrdw.o \
	$(OBJ)/vidhrdw/mugsmash_vidhrdw.o \
	$(OBJ)/vidhrdw/munchmo_vidhrdw.o \
	$(OBJ)/vidhrdw/mustache_vidhrdw.o \
	$(OBJ)/vidhrdw/mystston_vidhrdw.o \
	$(OBJ)/vidhrdw/mystwarr_vidhrdw.o \
	$(OBJ)/vidhrdw/namcona1_vidhrdw.o \
	$(OBJ)/vidhrdw/namconb1_vidhrdw.o \
	$(OBJ)/vidhrdw/namcos1_vidhrdw.o \
	$(OBJ)/vidhrdw/namcos21_vidhrdw.o \
	$(OBJ)/vidhrdw/namcos22_vidhrdw.o \
	$(OBJ)/vidhrdw/namcos2_vidhrdw.o \
	$(OBJ)/vidhrdw/namcos86_vidhrdw.o \
	$(OBJ)/vidhrdw/naughtyb_vidhrdw.o \
	$(OBJ)/vidhrdw/nbmj8688_vidhrdw.o \
	$(OBJ)/vidhrdw/nbmj8891_vidhrdw.o \
	$(OBJ)/vidhrdw/nbmj8991_vidhrdw.o \
	$(OBJ)/vidhrdw/nbmj9195_vidhrdw.o \
	$(OBJ)/vidhrdw/nemesis_vidhrdw.o \
	$(OBJ)/vidhrdw/neogeo_vidhrdw.o \
	$(OBJ)/vidhrdw/news_vidhrdw.o \
	$(OBJ)/vidhrdw/ninjakd2_vidhrdw.o \
	$(OBJ)/vidhrdw/ninjakid_vidhrdw.o \
	$(OBJ)/vidhrdw/ninjaw_vidhrdw.o \
	$(OBJ)/vidhrdw/nitedrvr_vidhrdw.o \
	$(OBJ)/vidhrdw/niyanpai_vidhrdw.o \
	$(OBJ)/vidhrdw/nmk16_vidhrdw.o \
	$(OBJ)/vidhrdw/nova2001_vidhrdw.o \
	$(OBJ)/vidhrdw/nycaptor_vidhrdw.o \
	$(OBJ)/vidhrdw/nyny_vidhrdw.o \
	$(OBJ)/vidhrdw/offtwall_vidhrdw.o \
	$(OBJ)/vidhrdw/ohmygod_vidhrdw.o \
	$(OBJ)/vidhrdw/ojankohs_vidhrdw.o \
	$(OBJ)/vidhrdw/omegaf_vidhrdw.o \
	$(OBJ)/vidhrdw/oneshot_vidhrdw.o \
	$(OBJ)/vidhrdw/orbit_vidhrdw.o \
	$(OBJ)/vidhrdw/othldrby_vidhrdw.o \
	$(OBJ)/vidhrdw/othunder_vidhrdw.o \
	$(OBJ)/vidhrdw/overdriv_vidhrdw.o \
	$(OBJ)/vidhrdw/pacland_vidhrdw.o \
	$(OBJ)/vidhrdw/pacman_vidhrdw.o \
	$(OBJ)/vidhrdw/pandoras_vidhrdw.o \
	$(OBJ)/vidhrdw/paradise_vidhrdw.o \
	$(OBJ)/vidhrdw/parodius_vidhrdw.o \
	$(OBJ)/vidhrdw/pass_vidhrdw.o \
	$(OBJ)/vidhrdw/pastelgl_vidhrdw.o \
	$(OBJ)/vidhrdw/pbaction_vidhrdw.o \
	$(OBJ)/vidhrdw/pcktgal_vidhrdw.o \
	$(OBJ)/vidhrdw/pgm_vidhrdw.o \
	$(OBJ)/vidhrdw/phoenix_vidhrdw.o \
	$(OBJ)/vidhrdw/pingpong_vidhrdw.o \
	$(OBJ)/vidhrdw/pirates_vidhrdw.o \
	$(OBJ)/vidhrdw/pitnrun_vidhrdw.o \
	$(OBJ)/vidhrdw/pkunwar_vidhrdw.o \
	$(OBJ)/vidhrdw/playch10_vidhrdw.o \
	$(OBJ)/vidhrdw/playmark_vidhrdw.o \
	$(OBJ)/vidhrdw/plygonet_vidhrdw.o \
	$(OBJ)/vidhrdw/polepos_vidhrdw.o \
	$(OBJ)/vidhrdw/policetr_vidhrdw.o \
	$(OBJ)/vidhrdw/poly.o \
	$(OBJ)/vidhrdw/polyplay_vidhrdw.o \
	$(OBJ)/vidhrdw/poolshrk_vidhrdw.o \
	$(OBJ)/vidhrdw/pooyan_vidhrdw.o \
	$(OBJ)/vidhrdw/popeye_vidhrdw.o \
	$(OBJ)/vidhrdw/popper_vidhrdw.o \
	$(OBJ)/vidhrdw/portrait_vidhrdw.o \
	$(OBJ)/vidhrdw/powerins_vidhrdw.o \
	$(OBJ)/vidhrdw/prehisle_vidhrdw.o \
	$(OBJ)/vidhrdw/psikyo4_vidhrdw.o \
	$(OBJ)/vidhrdw/psikyo_vidhrdw.o \
	$(OBJ)/vidhrdw/psikyosh_vidhrdw.o \
	$(OBJ)/vidhrdw/psx_vidhrdw.o \
	$(OBJ)/vidhrdw/psychic5_vidhrdw.o \
	$(OBJ)/vidhrdw/punchout_vidhrdw.o \
	$(OBJ)/vidhrdw/pushman_vidhrdw.o \
	$(OBJ)/vidhrdw/qix_vidhrdw.o \
	$(OBJ)/vidhrdw/quizdna_vidhrdw.o \
	$(OBJ)/vidhrdw/quizpani_vidhrdw.o \
	$(OBJ)/vidhrdw/raiden_vidhrdw.o \
	$(OBJ)/vidhrdw/raiders5_vidhrdw.o \
	$(OBJ)/vidhrdw/rallyx_vidhrdw.o \
	$(OBJ)/vidhrdw/rampart_vidhrdw.o \
	$(OBJ)/vidhrdw/rastan_vidhrdw.o \
	$(OBJ)/vidhrdw/realbrk_vidhrdw.o \
	$(OBJ)/vidhrdw/redalert_vidhrdw.o \
	$(OBJ)/vidhrdw/redclash_vidhrdw.o \
	$(OBJ)/vidhrdw/relief_vidhrdw.o \
	$(OBJ)/vidhrdw/renegade_vidhrdw.o \
	$(OBJ)/vidhrdw/resnet.o \
	$(OBJ)/vidhrdw/retofinv_vidhrdw.o \
	$(OBJ)/vidhrdw/rockola_vidhrdw.o \
	$(OBJ)/vidhrdw/rockrage_vidhrdw.o \
	$(OBJ)/vidhrdw/rocnrope_vidhrdw.o \
	$(OBJ)/vidhrdw/rohga_vidhrdw.o \
	$(OBJ)/vidhrdw/rollerg_vidhrdw.o \
	$(OBJ)/vidhrdw/rollrace_vidhrdw.o \
	$(OBJ)/vidhrdw/route16_vidhrdw.o \
	$(OBJ)/vidhrdw/rpunch_vidhrdw.o \
	$(OBJ)/vidhrdw/runaway_vidhrdw.o \
	$(OBJ)/vidhrdw/rungun_vidhrdw.o \
	$(OBJ)/vidhrdw/s2636_vidhrdw.o \
	$(OBJ)/vidhrdw/sauro_vidhrdw.o \
	$(OBJ)/vidhrdw/sbasketb_vidhrdw.o \
	$(OBJ)/vidhrdw/sbrkout_vidhrdw.o \
	$(OBJ)/vidhrdw/sbugger_vidhrdw.o \
	$(OBJ)/vidhrdw/sega_vidhrdw.o \
	$(OBJ)/vidhrdw/segac2_vidhrdw.o \
	$(OBJ)/vidhrdw/segaic16.o \
	$(OBJ)/vidhrdw/segaorun.o \
	$(OBJ)/vidhrdw/segar_vidhrdw.o \
	$(OBJ)/vidhrdw/segas16b.o \
	$(OBJ)/vidhrdw/segas18.o \
	$(OBJ)/vidhrdw/segas32.o \
	$(OBJ)/vidhrdw/segasyse_vidhrdw.o \
	$(OBJ)/vidhrdw/segaxbd.o \
	$(OBJ)/vidhrdw/seicross_vidhrdw.o \
	$(OBJ)/vidhrdw/sengokmj_vidhrdw.o \
	$(OBJ)/vidhrdw/senjyo_vidhrdw.o \
	$(OBJ)/vidhrdw/seta2_vidhrdw.o \
	$(OBJ)/vidhrdw/seta_vidhrdw.o \
	$(OBJ)/vidhrdw/sf1_vidhrdw.o \
	$(OBJ)/vidhrdw/shadfrce_vidhrdw.o \
	$(OBJ)/vidhrdw/shangha3_vidhrdw.o \
	$(OBJ)/vidhrdw/shangkid_vidhrdw.o \
	$(OBJ)/vidhrdw/shaolins_vidhrdw.o \
	$(OBJ)/vidhrdw/shisen_vidhrdw.o \
	$(OBJ)/vidhrdw/shootout_vidhrdw.o \
	$(OBJ)/vidhrdw/shuuz_vidhrdw.o \
	$(OBJ)/vidhrdw/sidearms_vidhrdw.o \
	$(OBJ)/vidhrdw/sidepckt_vidhrdw.o \
	$(OBJ)/vidhrdw/silkroad_vidhrdw.o \
	$(OBJ)/vidhrdw/simpsons_vidhrdw.o \
	$(OBJ)/vidhrdw/skullxbo_vidhrdw.o \
	$(OBJ)/vidhrdw/skychut_vidhrdw.o \
	$(OBJ)/vidhrdw/skydiver_vidhrdw.o \
	$(OBJ)/vidhrdw/skyfox_vidhrdw.o \
	$(OBJ)/vidhrdw/skykid_vidhrdw.o \
	$(OBJ)/vidhrdw/skyraid_vidhrdw.o \
	$(OBJ)/vidhrdw/slapfght_vidhrdw.o \
	$(OBJ)/vidhrdw/slapshot_vidhrdw.o \
	$(OBJ)/vidhrdw/snes_vidhrdw.o \
	$(OBJ)/vidhrdw/snk68_vidhrdw.o \
	$(OBJ)/vidhrdw/snk_vidhrdw.o \
	$(OBJ)/vidhrdw/snowbros_vidhrdw.o \
	$(OBJ)/vidhrdw/solomon_vidhrdw.o \
	$(OBJ)/vidhrdw/sonson_vidhrdw.o \
	$(OBJ)/vidhrdw/spacefb_vidhrdw.o \
	$(OBJ)/vidhrdw/spbactn_vidhrdw.o \
	$(OBJ)/vidhrdw/spcforce_vidhrdw.o \
	$(OBJ)/vidhrdw/spdodgeb_vidhrdw.o \
	$(OBJ)/vidhrdw/speedatk_vidhrdw.o \
	$(OBJ)/vidhrdw/speedbal_vidhrdw.o \
	$(OBJ)/vidhrdw/speedspn_vidhrdw.o \
	$(OBJ)/vidhrdw/spiders_vidhrdw.o \
	$(OBJ)/vidhrdw/splash_vidhrdw.o \
	$(OBJ)/vidhrdw/sprcros2_vidhrdw.o \
	$(OBJ)/vidhrdw/sprint2_vidhrdw.o \
	$(OBJ)/vidhrdw/sprint4_vidhrdw.o \
	$(OBJ)/vidhrdw/sprint8_vidhrdw.o \
	$(OBJ)/vidhrdw/spy_vidhrdw.o \
	$(OBJ)/vidhrdw/srmp2_vidhrdw.o \
	$(OBJ)/vidhrdw/srumbler_vidhrdw.o \
	$(OBJ)/vidhrdw/sshangha_vidhrdw.o \
	$(OBJ)/vidhrdw/sslam_vidhrdw.o \
	$(OBJ)/vidhrdw/ssozumo_vidhrdw.o \
	$(OBJ)/vidhrdw/sspeedr_vidhrdw.o \
	$(OBJ)/vidhrdw/ssrj_vidhrdw.o \
	$(OBJ)/vidhrdw/ssv_vidhrdw.o \
	$(OBJ)/vidhrdw/stactics_vidhrdw.o \
	$(OBJ)/vidhrdw/stadhero_vidhrdw.o \
	$(OBJ)/vidhrdw/starcrus_vidhrdw.o \
	$(OBJ)/vidhrdw/starfire_vidhrdw.o \
	$(OBJ)/vidhrdw/starshp1_vidhrdw.o \
	$(OBJ)/vidhrdw/stfight_vidhrdw.o \
	$(OBJ)/vidhrdw/stlforce_vidhrdw.o \
	$(OBJ)/vidhrdw/strnskil_vidhrdw.o \
	$(OBJ)/vidhrdw/stvvdp1_vidhrdw.o \
	$(OBJ)/vidhrdw/stvvdp2_vidhrdw.o \
	$(OBJ)/vidhrdw/subs_vidhrdw.o \
	$(OBJ)/vidhrdw/suna16_vidhrdw.o \
	$(OBJ)/vidhrdw/suna8_vidhrdw.o \
	$(OBJ)/vidhrdw/supbtime_vidhrdw.o \
	$(OBJ)/vidhrdw/superchs_vidhrdw.o \
	$(OBJ)/vidhrdw/superqix_vidhrdw.o \
	$(OBJ)/vidhrdw/suprloco_vidhrdw.o \
	$(OBJ)/vidhrdw/suprnova_vidhrdw.o \
	$(OBJ)/vidhrdw/suprridr_vidhrdw.o \
	$(OBJ)/vidhrdw/suprslam_vidhrdw.o \
	$(OBJ)/vidhrdw/surpratk_vidhrdw.o \
	$(OBJ)/vidhrdw/system16_vidhrdw.o \
	$(OBJ)/vidhrdw/system1_vidhrdw.o \
	$(OBJ)/vidhrdw/system24_vidhrdw.o \
	$(OBJ)/vidhrdw/tagteam_vidhrdw.o \
	$(OBJ)/vidhrdw/tail2nos_vidhrdw.o \
	$(OBJ)/vidhrdw/taito_b_vidhrdw.o \
	$(OBJ)/vidhrdw/taito_f2_vidhrdw.o \
	$(OBJ)/vidhrdw/taito_f3_vidhrdw.o \
	$(OBJ)/vidhrdw/taito_h_vidhrdw.o \
	$(OBJ)/vidhrdw/taito_l_vidhrdw.o \
	$(OBJ)/vidhrdw/taito_z_vidhrdw.o \
	$(OBJ)/vidhrdw/taitoair_vidhrdw.o \
	$(OBJ)/vidhrdw/taitosj_vidhrdw.o \
	$(OBJ)/vidhrdw/tankbatt_vidhrdw.o \
	$(OBJ)/vidhrdw/tankbust_vidhrdw.o \
	$(OBJ)/vidhrdw/taotaido_vidhrdw.o \
	$(OBJ)/vidhrdw/targeth_vidhrdw.o \
	$(OBJ)/vidhrdw/tatsumi.o \
	$(OBJ)/vidhrdw/taxidrvr_vidhrdw.o \
	$(OBJ)/vidhrdw/tbowl_vidhrdw.o \
	$(OBJ)/vidhrdw/tceptor_vidhrdw.o \
	$(OBJ)/vidhrdw/tecmo16_vidhrdw.o \
	$(OBJ)/vidhrdw/tecmo_vidhrdw.o \
	$(OBJ)/vidhrdw/tehkanwc_vidhrdw.o \
	$(OBJ)/vidhrdw/terracre_vidhrdw.o \
	$(OBJ)/vidhrdw/tetrisp2_vidhrdw.o \
	$(OBJ)/vidhrdw/thedeep_vidhrdw.o \
	$(OBJ)/vidhrdw/thepit_vidhrdw.o \
	$(OBJ)/vidhrdw/thief_vidhrdw.o \
	$(OBJ)/vidhrdw/thoop2_vidhrdw.o \
	$(OBJ)/vidhrdw/thunderj_vidhrdw.o \
	$(OBJ)/vidhrdw/thunderx_vidhrdw.o \
	$(OBJ)/vidhrdw/tickee_vidhrdw.o \
	$(OBJ)/vidhrdw/tigeroad_vidhrdw.o \
	$(OBJ)/vidhrdw/timelimt_vidhrdw.o \
	$(OBJ)/vidhrdw/timeplt_vidhrdw.o \
	$(OBJ)/vidhrdw/tlc34076.o \
	$(OBJ)/vidhrdw/tmnt_vidhrdw.o \
	$(OBJ)/vidhrdw/tms34061_vidhrdw.o \
	$(OBJ)/vidhrdw/tnzs_vidhrdw.o \
	$(OBJ)/vidhrdw/toaplan1_vidhrdw.o \
	$(OBJ)/vidhrdw/toaplan2_vidhrdw.o \
	$(OBJ)/vidhrdw/toki_vidhrdw.o \
	$(OBJ)/vidhrdw/toobin_vidhrdw.o \
	$(OBJ)/vidhrdw/topspeed_vidhrdw.o \
	$(OBJ)/vidhrdw/toypop_vidhrdw.o \
	$(OBJ)/vidhrdw/tp84_vidhrdw.o \
	$(OBJ)/vidhrdw/trackfld_vidhrdw.o \
	$(OBJ)/vidhrdw/travrusa_vidhrdw.o \
	$(OBJ)/vidhrdw/triplhnt_vidhrdw.o \
	$(OBJ)/vidhrdw/troangel_vidhrdw.o \
	$(OBJ)/vidhrdw/truco_vidhrdw.o \
	$(OBJ)/vidhrdw/tryout_vidhrdw.o \
	$(OBJ)/vidhrdw/tsamurai_vidhrdw.o \
	$(OBJ)/vidhrdw/ttmahjng_vidhrdw.o \
	$(OBJ)/vidhrdw/tubep_vidhrdw.o \
	$(OBJ)/vidhrdw/tumblep_vidhrdw.o \
	$(OBJ)/vidhrdw/tunhunt_vidhrdw.o \
	$(OBJ)/vidhrdw/turbo_vidhrdw.o \
	$(OBJ)/vidhrdw/tutankhm_vidhrdw.o \
	$(OBJ)/vidhrdw/twin16_vidhrdw.o \
	$(OBJ)/vidhrdw/twincobr_vidhrdw.o \
	$(OBJ)/vidhrdw/ultraman_vidhrdw.o \
	$(OBJ)/vidhrdw/undrfire_vidhrdw.o \
	$(OBJ)/vidhrdw/unico_vidhrdw.o \
	$(OBJ)/vidhrdw/usgames_vidhrdw.o \
	$(OBJ)/vidhrdw/vaportra_vidhrdw.o \
	$(OBJ)/vidhrdw/vastar_vidhrdw.o \
	$(OBJ)/vidhrdw/vball_vidhrdw.o \
	$(OBJ)/vidhrdw/vector.o \
	$(OBJ)/vidhrdw/vendetta_vidhrdw.o \
	$(OBJ)/vidhrdw/vicdual_vidhrdw.o \
	$(OBJ)/vidhrdw/victory_vidhrdw.o \
	$(OBJ)/vidhrdw/videopin_vidhrdw.o \
	$(OBJ)/vidhrdw/vigilant_vidhrdw.o \
	$(OBJ)/vidhrdw/vindictr_vidhrdw.o \
	$(OBJ)/vidhrdw/volfied_vidhrdw.o \
	$(OBJ)/vidhrdw/voodoo_vidhrdw.o \
	$(OBJ)/vidhrdw/vsnes_vidhrdw.o \
	$(OBJ)/vidhrdw/vulgus_vidhrdw.o \
	$(OBJ)/vidhrdw/warpwarp_vidhrdw.o \
	$(OBJ)/vidhrdw/warriorb_vidhrdw.o \
	$(OBJ)/vidhrdw/wc90_vidhrdw.o \
	$(OBJ)/vidhrdw/wc90b_vidhrdw.o \
	$(OBJ)/vidhrdw/wecleman_vidhrdw.o \
	$(OBJ)/vidhrdw/welltris_vidhrdw.o \
	$(OBJ)/vidhrdw/wgp_vidhrdw.o \
	$(OBJ)/vidhrdw/williams_vidhrdw.o \
	$(OBJ)/vidhrdw/wiping_vidhrdw.o \
	$(OBJ)/vidhrdw/wiz_vidhrdw.o \
	$(OBJ)/vidhrdw/wolfpack_vidhrdw.o \
	$(OBJ)/vidhrdw/wrally_vidhrdw.o \
	$(OBJ)/vidhrdw/wwfsstar_vidhrdw.o \
	$(OBJ)/vidhrdw/wwfwfest_vidhrdw.o \
	$(OBJ)/vidhrdw/xain_vidhrdw.o \
	$(OBJ)/vidhrdw/xevious_vidhrdw.o \
	$(OBJ)/vidhrdw/xexex_vidhrdw.o \
	$(OBJ)/vidhrdw/xmen_vidhrdw.o \
	$(OBJ)/vidhrdw/xorworld_vidhrdw.o \
	$(OBJ)/vidhrdw/xxmissio_vidhrdw.o \
	$(OBJ)/vidhrdw/xybots_vidhrdw.o \
	$(OBJ)/vidhrdw/xyonix_vidhrdw.o \
	$(OBJ)/vidhrdw/yard_vidhrdw.o \
	$(OBJ)/vidhrdw/yiear_vidhrdw.o \
	$(OBJ)/vidhrdw/yunsun16_vidhrdw.o \
	$(OBJ)/vidhrdw/yunsung8_vidhrdw.o \
	$(OBJ)/vidhrdw/zac2650_vidhrdw.o \
	$(OBJ)/vidhrdw/zaccaria_vidhrdw.o \
	$(OBJ)/vidhrdw/zaxxon_vidhrdw.o \
	$(OBJ)/vidhrdw/zerozone_vidhrdw.o \
	$(OBJ)/vidhrdw/zodiack_vidhrdw.o

